#!/bin/sh

Usage() {
	echo "Usage: $0 {-h | [-r tag] [[-a newfile... -f] file...] }"
	exit 1
}

if [ "$1" = "-h" ]; then
	Usage
fi

files=""
newfiles=""
TAG=""

if [ "$1" = "-r" ]; then
	if [ -z "$2" ]; then
		Usage
	fi
	TAG="-r $2"
	shift 2
fi

tempDir=`mktemp -d -p . -t ".cvdf_XXXX"` || exit 1
temprc=`mktemp -p $tempDir -t "vim.XXXX"` || exit 1
tempcup=`mktemp -p $tempDir -t "cup.XXXX"` || exit 1

if [ -z $1 ]; then
	cvs -nq up -Pd > $tempcup
	newfiles=`grep ^A $tempcup | cut -d' ' -f2`
	files=`grep ^M $tempcup | cut -d' ' -f2`
else
	if [ "$1" = "-a" ]; then
		shift
		for f in $@; do
			shift
			if [ "$f" = "-f" ]; then
				break
			elif [ -f "$f" ]; then
				newfiles="${newfiles} $f"
			else
				echo "$f not found!"
			fi
		done
	fi
	for f in $@; do
		if [ -f "$f" ]; then
			files="${files} $f"
		else
			echo "$f not found!"
		fi
	done
fi

for local in $files; do
	prefix=`basename $local | cut -d'.' -f1`
	temp=`mktemp -p $tempDir -t "${prefix}_XXXX"` || exit 1

	ext=`basename $local | cut -d'.' -f2`
	if [ "$prefix" != "$ext" ]; then
		server="${temp}.${ext}"
		mv $temp $server
	else
		server="${temp}"
	fi
	cvs -q up -p $TAG $local > $server

	echo "tabe $server" >> $temprc
	echo "vert diffsplit $local" >> $temprc
done
for local in $newfiles; do
	echo "tabe $local" >> $temprc
done
echo "tabfirst" >> $temprc
echo "tabclose" >> $temprc
vim -S $temprc 
rm -rf $tempDir

