#!/bin/bash
# This hook is invoked when a git-checkout is run after having updated the worktree.
# The hook is given three parameters: the ref of the previous HEAD, 
# the ref of the new HEAD (which may or may not have changed), 
# and a flag indicating whether the checkout was a branch checkout (changing branches, flag=1)
# or a file checkout (retrieving a file from the index, flag=0).
# This hook cannot affect the outcome of git-checkout.
# This hook can be used to perform repository validity checks, 
# auto-display differences from the previous HEAD if different, or set working dir metadata properties.


PLATFORMS="x64 854x"
DetectPlatformDir()
{
	if ! echo $1| grep ds\.base >/dev/null; then
		echo Not a project inside ds.base ! Stop hard link action !
		exit 1
	fi
	# remove ds.base , branch dir
	PLATFORMS=`ls -d ${1%%ds.*}ds.*| grep -v '-'| grep -v base| sed 's/.*ds.//g'`

}

# flag = 1 => change branches
if [ "$3" -eq 1 ]; then
	echo "Trying to do hard link ..."
	CWD=`pwd`
	basedir=`dirname $CWD`

	[ -n "${PLATFORMS}" ] || DetectPlatformDir $CWD
	for plat in ${PLATFORMS}; do
		echo "$CWD -> ${basedir/base/$plat}"
		cp -alf $CWD ${basedir/base/$plat}
	done
fi
